[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 5
decoder_hidden_dim = 128
nl = "sine"                     # 'sine' | 'relu' | 'softplus'
sphere_init_params = [1.6, 0.1]
init_type = "mfgi"              # 'siren' | 'geometric_sine' | 'geometric_relu' | 'mfgi'
neuron_type = "quadratic"       # 'linear' | 'quadratic'

[loss]
loss_type = "igr_w_heat" # SPIN: "igr[_wo_eik]_w_heat", StEik: "siren[_wo_n]_w_div", "siren[_wo_n]", "igr[_wo_n]"
loss_weights = [ 4, 0, 0, 0.1, 0, 0, 1, ] # sdf, inter, normal, eikonal, div, latent, heat
div_type = "dir_l1" # 'dir_l1' | 'dir_l2' | 'full_l1' | 'full_l2'
div_decay = "linear" # 'linear' | 'quintic' | 'step'
div_decay_params = [ 100.0, 0.2, 100.0, 0.4, 0.0, 0.0, ] # start, (location, value)*, end
heat_decay = "linear" # 'linear' | 'quintic' | 'step'
heat_decay_params = [1, 0.2, 1, 0.4, 0.1, 0.1] # start, (location, value)*, end
# heat_lambda_decay = "linear" # 'linear' | 'quintic' | 'step'
# heat_lambda_decay_params = [0.1, 0.4, 10.0, 0.6, 10.0, 10.0] # start, (location, value)*, end

[sampling]
grid_res = 256
nonmnfld_sample_type = "uniform"
n_random_samples = 8192          # only used when nonmnfld_sample_type != "grid"
n_points = 15000                 # samples on the manifold
grid_range = 1.2
nonmnfld_sample_std2 = 0.027     # random sample variance (std^3 in 3d, name TBD)

[training]
task = "3d"
n_iterations = 10000  # training iterations
gpu_idx = 0
lr = 5e-5
grad_clip_norm = 10.0
heat_lambda = 10.0
vis_interval = 100
log_interval = 100

[visualization]
vis_grid_res = 256
vis_grid_range = 1.2
vis_contour_interval = 0.025
