[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 5
decoder_hidden_dim = 128
nl = "softplus"                 # 'sine' | 'relu' | 'softplus'
sphere_init_params = [0.0, 1.0]
init_type = "geometric_relu_2d"
neuron_type = "linear"          # 'linear' | 'quadratic'

[loss]
loss_type = "everything_including_div_heat_sal"
loss_weights = [ 90, 0, 0, 0.01, 0, 0, 0.2] # sdf, inter, normal, eikonal, div, latent, heat]

div_type = "full_l1" # "full_l1" == digs, "dir_l1" == steik
div_decay = "linear"
# div_decay_params = [1e2, 0.2, 1e2, 0.4, 0.0, 0.0]
div_decay_params = [0, 0] # start, end keep 0


eikonal_decay = "linear" # 'linear' | 'quintic' | 'step'
eikonal_decay_params = [0.01, 0.7, 0.01, 5] # start, (location, value)*, end
# heat_lambda_decay = "linear" # 'linear' | 'quintic' | 'step'
# heat_lambda_decay_params = [0.1, 0.4, 10.0, 0.6, 10.0, 10.0] # start, (location, value)*, end

[sampling]
grid_res = 256
nonmnfld_sample_type = "uniform_central_gaussian"
n_random_samples = 4096
n_points = 15000
grid_range = 1.5
nonmnfld_sample_std = 0.5

[training]
train = true
eval = true
task = "2d"
n_iterations = 20000
gpu_idx = 0
lr = 1e-4
grad_clip_norm = 10.0
heat_lambda = 60.0
vis_interval = 2000
log_interval = 2000

[visualization]
vis_grid_res = 256
vis_grid_range = 1.2
vis_contour_interval = 0.025
vis_normals = true
n_vis_normals = 100
vis_heat = true
vis_gt_shape = true
save_video = true
video_fps = 6