[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 5
decoder_hidden_dim = 128
nl = "softplus"
sphere_init_params = [1.6, 1.0]
init_type = "geometric_relu_2d"
neuron_type = "linear"

[loss]
loss_type = "igr_w_heat"
loss_weights = [ 90, 0, 0, 0.01, 0, 0, 0.5]
heat_decay = "linear"
heat_decay_params = [0.2, 0.8, 0.2, 0.9, 0.01, 0.0]
eikonal_decay = "linear"
eikonal_decay_params = [0.01, 0.7, 0.01, 3]

[sampling]
grid_res = 256
nonmnfld_sample_type = "uniform_central_gaussian"
n_random_samples = 4096
n_points = 15000
grid_range = 1.5
nonmnfld_sample_std = 0.5

[training]
train = false
eval = true
task = "2d"
n_iterations = 1000
gpu_idx = 0
lr = 5e-5
grad_clip_norm = 10.0
heat_lambda = 10.0
log_interval = 100
compute_losses_on_vis_grid = 0

[visualization]
vis_interval = 100
vis_grid_res = 256
vis_grid_range = 1.2
vis_contour_interval = 0.025
vis_normals = true
n_vis_normals = 10
vis_heat = true
vis_diff = true
save_video = true
vis_final = true
compute_metrics = true
