[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 4
decoder_hidden_dim = 256
nl = "sine"
sphere_init_params = [1.6, 0.1]
init_type = "siren"
neuron_type = "linear"

[loss]
loss_type = "cad"
loss_weights = [7e3, 6e2, 1e2, 5e1, 0, 0, 0, 0, 0, 10]
cad_decay = 'linear'
cad_decay_params = [10, 0.2, 10, 0.5, 0.001, 0]

[sampling]
grid_res = 256
nonmnfld_sample_type = "uniform"
# nonmnfld_sample_type = "uniform_central_gaussian"
n_random_samples = 15000
n_points = 15000
grid_range = 1.1
nonmnfld_sample_std = 0.5
pcd_scale_method = "default"
# seed = 20241101

[training]
train = true
eval = true
task = "3d"
n_iterations = 10001
gpu_idx = 0
lr = 5e-5
grad_clip_norm = 10.0
vis_interval = 500
log_interval = 100

[visualization]
vis_grid_res = 256
vis_grid_range = 1.0
vis_contour_interval = 0.025
# vis_heat = true
# save_video = true
# video_fps = 6
# vis_final = true
vis_contour_range = [-1.0, 1.0]
