[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 5
decoder_hidden_dim = 128
nl = "softplus"                 # 'sine' | 'relu' | 'softplus'
sphere_init_params = [0.0, 1.0]
init_type = "geometric_relu_2d"    # 'siren' | 'geometric_sine' | 'geometric_relu' | 'mfgi'
neuron_type = "linear"          # 'linear' | 'quadratic'

[loss]
loss_type = "igr_w_heat" # 'siren_wo_n_w_div' | 'siren_wo_n' | 'siren_w_div' | 'siren'
loss_weights = [ 40, 0, 0, 0.01, 0, 0, 0.2] # sdf, inter, normal, eikonal, div, latent, heat
heat_decay = "linear" # 'linear' | 'quintic' | 'step'
heat_decay_params = [0.2, 0.045, 0.2, 0.06, 0.1, 0.1] # start, (location, value)*, end
eikonal_decay = "linear" # 'linear' | 'quintic' | 'step'
eikonal_decay_params = [0.01, 0.03, 0.01, 0.06, 0, 0] # start, (location, value)*, end
heat_lambda_decay = "linear" # 'linear' | 'quintic' | 'step'
heat_lambda_decay_params = [60, 0.03, 60, 0.06, 0.2, 0.2] # start, (location, value)*, end

[sampling]
grid_res = 256
nonmnfld_sample_type = "uniform_central_gaussian"
n_random_samples = 32766
n_points = 15000
grid_range = 1.5
nonmnfld_sample_std = 0.5

[training]
train = true
eval = true
task = "2d"
n_iterations = 400000
gpu_idx = 0
lr = 1e-5
grad_clip_norm = 10.0
heat_lambda = 60
vis_interval = 4000
log_interval = 1000

[visualization]
vis_grid_res = 256
vis_grid_range = 1.2
vis_contour_interval = 0.01
vis_normals = true
n_vis_normals = 100
vis_heat = true
vis_gt_shape = true
save_video = true
video_fps = 6
compute_losses_on_vis_grid = 0