[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 5
decoder_hidden_dim = 128
nl = "softplus"                 # 'sine' | 'relu' | 'softplus'
sphere_init_params = [0.0, 1.0]
init_type = "geometric_relu_2d"    # 'siren' | 'geometric_sine' | 'geometric_relu' | 'mfgi'
neuron_type = "linear"          # 'linear' | 'quadratic'

[loss]
loss_type = "igr_w_heat"
loss_weights = [90, 0, 0, 0.01, 0, 0, 0.5]
heat_decay = "linear"
heat_decay_params = [0.2, 0.8, 0.2, 0.9, 0.03, 0.02]
eikonal_decay = "linear"
eikonal_decay_params = [0.01, 0.7, 0.01, 5]

[sampling]
grid_res = 256
nonmnfld_sample_type = "uniform_central_gaussian"
n_random_samples = 4096
n_points = 15000
grid_range = 1.5
nonmnfld_sample_std = 0.5

[training]
train = true
eval = true
task = "2d"
n_iterations = 10000
gpu_idx = 0
lr = 1e-4
grad_clip_norm = 10.0
heat_lambda = 60.0
vis_interval = 200
log_interval = 100

[visualization]
vis_grid_res = 256
vis_grid_range = 2.0
vis_contour_interval = 0.05
# vis_normals = true
# n_vis_normals = 100
# vis_heat = true
vis_gt_shape = true
# save_video = true
# video_fps = 6