[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 5
decoder_hidden_dim = 128
nl = "softplus"
sphere_init_params = [1.6, 1.0]
init_type = "geometric_relu"
neuron_type = "linear"

[loss]
loss_type = "phase"
loss_weights = [0.1, 0, 0, 0.1, 0, 0, 0, 1]
# loss_weights = [100, 0, 0, 10, 0, 0, 0, 10]

[sampling]
grid_res = 256
nonmnfld_sample_type = "uniform"
n_random_samples = 4096
n_points = 100
grid_range = 1.2
pcd_scale_method = "default"

[training]
train = true
eval = true
task = "2d"
n_iterations = 10001
gpu_idx = 0
lr = 5e-5
grad_clip_norm = 10.0
phase_epsilon = 0.01
vis_interval = 100
log_interval = 100

[visualization]
vis_grid_res = 256
vis_grid_range = 1.2
vis_contour_interval = 0.025
# vis_normals = true
# n_vis_normals = 100
# vis_heat = true
vis_gt_shape = true
# save_video = true
# video_fps = 6