[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 5
decoder_hidden_dim = 128
nl = "relu"
sphere_init_params = [1.6, 1.0]
init_type = "geometric_relu"
neuron_type = "linear"

[loss]
loss_type = 'sal'
loss_weights = [100, 0, 0, 0, 0, 20, 0]

[sampling]
grid_res = 256
nonmnfld_sample_type = "uniform"
n_random_samples = 15000
n_points = 15000
grid_range = 1.2
#nonmnfld_sample_std = 1.0

[training]
train = true
eval = false
task = "3d"
n_iterations = 10000
gpu_idx = 0
lr = 1e-5
grad_clip_norm = 10.0
vis_interval = 100
log_interval = 100

[visualization]
vis_grid_res = 256
vis_grid_range = 1.2
vis_contour_interval = 0.025
# vis_normals = true
# n_vis_normals = 100
save_video = true
compute_losses_on_vis_grid = false
video_fps = 6
# vis_contour_range = [-1.0, 1.0]
# vis_gt_shape = true