[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 5
decoder_hidden_dim = 128
nl = "sine"
sphere_init_params = [1.6, 0.1]
init_type = "siren"
neuron_type = "linear"

[loss]
loss_type = "siren_wo_n"
loss_weights = [90, 0, 0, 1, 0, 0, 1]

[sampling]
grid_res = 256
nonmnfld_sample_type = "uniform"
n_random_samples = 15000
n_points = 15000
grid_range = 1.2
nonmnfld_sample_std = 0.5

[training]
train = true
eval = true
task = "3d"
n_iterations = 10000
gpu_idx = 0
lr = 1e-4
grad_clip_norm = 10.0
heat_lambda = 8.0
vis_interval = 100
log_interval = 100

[visualization]
vis_grid_res = 256
vis_grid_range = 1.2
vis_contour_interval = 0.025
# vis_normals = true
# n_vis_normals = 100
# vis_heat = true
# vis_gt_shape = false
save_video = true
video_fps = 6
compute_losses_on_vis_grid = false
