[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 5
decoder_hidden_dim = 128
nl = "sine"
sphere_init_params = [1.6, 0.1]
init_type = "mfgi"
neuron_type = "quadratic"
n_repeat_period = 30

[loss]
loss_type = "igr_w_heat"
loss_weights = [200, 0, 0, 1, 0, 0, 1]
heat_decay = "linear"                               
heat_decay_params = [10, 0.4, 10, 0.6, 5, 3] 
eikonal_decay = "linear"                            
eikonal_decay_params = [1, 0.6, 1, 10]         
heat_lambda_decay = "linear"
heat_lambda_decay_params = [6, 0.2, 6, 0.4, 20, 30]

[sampling]
grid_res = 256
nonmnfld_sample_type = "uniform"
# nonmnfld_sample_type = "uniform_central_gaussian"
n_random_samples = 15000
n_points = 15000
grid_range = 1.1
nonmnfld_sample_std = 0.8

[training]
train = true
eval = true
task = "3d"
n_iterations = 10000
gpu_idx = 0
lr = 5e-5
grad_clip_norm = 10.0
heat_lambda = 12.0
vis_interval = 200
log_interval = 100

[visualization]
vis_grid_res = 256
vis_grid_range = 1.1
vis_contour_interval = 0.025
# vis_heat = true
# save_video = true
# video_fps = 6
# vis_final = true