[paths]
model_dir = "models"

[network]
decoder_n_hidden_layers = 4
decoder_hidden_dim = 128
nl = "sine"
sphere_init_params = [1.6, 1.0]
init_type = "mfgi"
neuron_type = "quadratic"

[loss]
loss_type = 'siren_wo_n_w_div'
loss_weights = [3e3, 1e2, 1e2, 5e1, 1e2, 0.0, 0.0]
div_type = "dir_l1"
div_decay = "linear"
div_decay_params = [1e2, 0.2, 1e2, 0.4, 0.0, 0.0]

[sampling]
grid_res = 256
nonmnfld_sample_type = "grid"
n_random_samples = 15000
n_points = 15000
grid_range = 1.2
# nonmnfld_sample_std = 1.0

[training]
train = true
eval = true
task = "2d"
n_iterations = 20000
gpu_idx = 0
lr = 5e-5
# heat_lambda = 60.0
vis_interval = 1000
log_interval = 1000
num_workers = 2
clip_grad_norm = 0

[visualization]
vis_grid_res = 256
vis_grid_range = 1.0
vis_contour_interval = 0.025
vis_normals = true
n_vis_normals = 100
save_video = true
video_fps = 6
# vis_contour_range = [-1.0, 1.0]
vis_gt_shape = true